version: 0.2

env:
  variables:
    TF_VERSION: "1.7.2"

phases:
  install:
    commands:
      - echo install step...
      - env
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"
      - chmod +x terraform
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo setting AWS env vars
      - export AWS_ACCESS_KEY_ID=$(pass TF_key_value)
      - export AWS_SECRET_ACCESS_KEY=$(pass TF_secret_value)
      - echo logging in to AWS ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 962804699607.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - pwd
      - cd "tf/"
      - terraform init 
      - terraform apply -auto-approve
      - cd ".."
      - echo build Docker image on `date`
      - docker build -t grp1-tf-cp2-ecr-repo:latest .
      - docker tag grp1-tf-cp2-ecr-repo:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/grp1-tf-cp2-ecr-repo:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/grp1-tf-cp2-ecr-repo:latest